# Generated by Django 5.2 on 2025-04-22 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='deta_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 13, 47, 6, 350921, tzinfo=datetime.timezone.utc)),
        ),
    ]
