# Generated by Django 5.2 on 2025-04-22 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_deta_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='deta_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
